import { promises as fs } from 'fs';
import path, { join } from 'path';
import { createInterface } from 'readline';
import { colorize, waitForEnterInInteractiveMode, writeFileAtomic } from '../utils/misc-utils.js';
import { PROJECT_DIR } from '../config/paths.js';
import { getProjectDisplayPath, getUserProjectQuestionsFile, getUserProjectConfigFile } from '../config/user-paths.js';
import { getModuleNameFromUrl } from '../utils/misc-utils.js';
import { USER_QUESTION_TEMPLATES_DIR } from '../config/user-paths.js';
import { logger } from '../utils/compact-logger.js';
import { sanitizeProjectName } from '../utils/project-utils.js';
import { PipelineCriticalError } from '../utils/pipeline-errors.js';
import { parseProjectNewArgs, resolveQuestionCount } from './project-new-args.js';

const CURRENT_MODULE_NAME = getModuleNameFromUrl(import.meta.url);

// Default configuration
const DEFAULT_QUESTION_COUNT = 3;
const MAX_QUESTIONS = 3;
const DEFAULT_AI_PRESET = 'ai_chats_with_search';
const DEFAULT_TEMPLATE_NAME = 'default.md';

interface ProjectSetupConfig {
  projectName: string;
  display_name: string;
  description: string;
  questions: string[];
  ai_preset: string;
}

// ============================================================================
// Helper Functions
// ============================================================================

function question(prompt: string): Promise<string> {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

/**
 * Ask a Y/n or y/N confirmation question
 */
async function confirmAction(prompt: string, defaultYes: boolean = true): Promise<boolean> {
  const suffix = defaultYes ? ' (Y/n): ' : ' (y/N): ';
  const answer = await question(prompt + suffix);

  if (answer === '') {
    return defaultYes;
  }

  return answer.toLowerCase() === 'y';
}

/**
 * Convert string to title case
 */
function toTitleCase(str: string): string {
  return str
    .toLowerCase()
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Load the default question template
 */
async function loadDefaultTemplate(): Promise<string[]> {
  const templatePath = join(USER_QUESTION_TEMPLATES_DIR, DEFAULT_TEMPLATE_NAME);

  try {
    const content = await fs.readFile(templatePath, 'utf-8');
    const lines = content.split('\n').filter(line => line.trim());

    // Filter out comment lines (starting with #)
    const questions = lines.filter(line => !line.trim().startsWith('#'));

    if (questions.length === 0) {
      throw new PipelineCriticalError(
        `No questions found in default template: ${templatePath}`,
        CURRENT_MODULE_NAME
      );
    }

    return questions;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      throw new PipelineCriticalError(
        `Default template not found: ${templatePath}`,
        CURRENT_MODULE_NAME
      );
    }
    throw error;
  }
}

/**
 * Generate unique project name, handling duplicates
 */
async function generateUniqueProjectName(baseName: string): Promise<string> {
  const sanitized = sanitizeProjectName(baseName);
  let projectName = sanitized;
  let counter = 1;

  while (true) {
    const projectDir = PROJECT_DIR(projectName);
    try {
      await fs.access(projectDir);
      // Directory exists, try with a number
      projectName = `${sanitized}_${counter}`;
      counter++;
    } catch {
      // Directory doesn't exist, we can use this name
      return projectName;
    }
  }
}

/**
 * Save project configuration and questions
 */
async function saveProject(config: ProjectSetupConfig): Promise<void> {
  const projectDir = PROJECT_DIR(config.projectName);
  await fs.mkdir(projectDir, { recursive: true });

  // Save questions
  const questionsContent = `# Questions for ${config.display_name}
# ${config.description}
# Generated by aicw-ai-mentions

${config.questions.join('\n')}
`;

  const questionsPath = getUserProjectQuestionsFile(config.projectName);
  await writeFileAtomic(questionsPath, questionsContent);

  // Save project configuration
  const projectConfig = {
    name: config.projectName,
    display_name: config.display_name,
    description: config.description,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ai_preset: config.ai_preset
  };

  const configPath = getUserProjectConfigFile(config.projectName);
  await writeFileAtomic(configPath, JSON.stringify(projectConfig, null, 2));
}

// ============================================================================
// Step Functions
// ============================================================================

/**
 * Step 1: Get topic from user
 */
async function getTopicStep(): Promise<string> {
  logger.log('\n' + colorize('Step 1: Enter Topic', 'bright'));
  logger.log(colorize('What topic would you like to track AI mentions for?', 'dim'));
  logger.log(colorize('Examples: "email marketing", "project management tools", "electric vehicles"', 'dim'));

  while (true) {
    const topic = await question('\nEnter topic: ');

    if (!topic) {
      logger.error('Topic cannot be empty. Please try again.');
      continue;
    }

    return topic;
  }
}

/**
 * Step 2: Get question count from user
 */
async function getQuestionCountStep(): Promise<number> {
  logger.log('\n' + colorize('Step 2: Number of Questions', 'bright'));
  logger.log(colorize(`How many questions to generate? (1-${MAX_QUESTIONS})`, 'dim'));

  while (true) {
    const input = await question(`\nNumber of questions [${DEFAULT_QUESTION_COUNT}]: `);

    // Use default if empty
    if (!input) {
      return DEFAULT_QUESTION_COUNT;
    }

    const count = parseInt(input);

    if (isNaN(count) || count < 1 || count > MAX_QUESTIONS) {
      logger.error(`Please enter a number between 1 and ${MAX_QUESTIONS}.`);
      continue;
    }

    return count;
  }
}

/**
 * Show preview of questions and get confirmation
 */
async function showPreviewAndConfirm(displayName: string, questions: string[]): Promise<boolean> {
  logger.log('\n' + colorize('─'.repeat(50), 'dim'));
  logger.log(colorize(`📋 Preview: "${displayName}" with ${questions.length} questions:`, 'bright'));
  logger.log('');

  questions.forEach((q, i) => {
    logger.log(`  ${colorize(`${i + 1}.`, 'cyan')} ${q}`);
  });

  logger.log('\n' + colorize('─'.repeat(50), 'dim'));

  return await confirmAction('\nCreate project?', true);
}

// ============================================================================
// Main Function
// ============================================================================

async function main() {
  const cliArgs = parseProjectNewArgs(process.argv.slice(2));
  const isSubjectProvided = Boolean(cliArgs.topic);

  logger.log(colorize('\n🚀 aicw-ai-mentions - New Project Setup', 'bright'));
  logger.log(colorize('━'.repeat(50), 'dim'));

  // Main loop to allow going back
  while (true) {
    // Step 1: Get topic
    const topic = cliArgs.topic || await getTopicStep();

    // Step 2: Get question count
    const questionCount = isSubjectProvided
      ? resolveQuestionCount(cliArgs.questionCount, DEFAULT_QUESTION_COUNT, MAX_QUESTIONS)
      : await getQuestionCountStep();

    // Load template and generate questions
    const templateQuestions = await loadDefaultTemplate();
    const questions = templateQuestions
      .slice(0, questionCount)
      .map(q => q.replace(/{{SUBJECT}}/g, topic));

    // Generate project metadata
    const displayName = toTitleCase(topic);
    const projectName = await generateUniqueProjectName(topic);

    // Show preview and confirm for interactive setup. CLI scan mode should run without prompts.
    const confirmed = isSubjectProvided ? true : await showPreviewAndConfirm(displayName, questions);

    if (!confirmed) {
      logger.log(colorize('\nStarting over...', 'dim'));
      continue;
    }

    // Save project
    try {
      await saveProject({
        projectName,
        display_name: displayName,
        description: `LLM perception scan for ${topic}`,
        questions,
        ai_preset: DEFAULT_AI_PRESET
      });

      logger.success(`\n✓ Project "${displayName}" created successfully!`);
      logger.log(colorize(`  Saved to: ${getProjectDisplayPath(projectName)}`, 'dim'));
      if (isSubjectProvided) {
        logger.log(colorize(`  Generated ${questions.length} default scan questions`, 'dim'));
      }

      // Output marker for pipeline to capture
      console.log(`AICW_OUTPUT_STRING:${projectName}`);

      if (!isSubjectProvided) {
        await waitForEnterInInteractiveMode();
      }

      return projectName;

    } catch (error) {
      logger.error('\n✗ Failed to save project');
      console.error(error);
      throw new Error('Failed to save project');
    }
  }
}

main().catch(err => {
  logger.error('Failed to create project:');
  console.error(err);
  throw err;
});
